### ISSUE TITLE
Initialization of ResNet50 Models and Paths in Config

### ISSUE THREAD

**Issue by ziqipang** [megvii-research/PETR#1]
Hi Guys,

Thanks for the nice work! I have some questions and not sure if my understanding is correct.
1. From the [config file](https://github.com/megvii-research/PETR/blob/3617936cd5f6320eb046738acf8f9847b3c8101f/projects/configs/petr/petr_r50dcn_gridmask_p4.py#L41), the models for ResNet-50 are initialized from a special pth file. However, it is missing in the provided model weights.
2. I guess you want to change the `data_root` in the configuration files, such as [this line](https://github.com/megvii-research/PETR/blob/3617936cd5f6320eb046738acf8f9847b3c8101f/projects/configs/petr/petr_r50dcn_gridmask_p4.py#L116), to `./data/nuscenes/` to fit the directory structure in README.

Thanks again for the help! Please help me check with the pretrained weights.

**Comment by yingfei1016** [comment]
Hi,
Thanks for your attention !
1. The model  weights pretrained on ImageNet can be find [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/model_zoo/open_mmlab.json).
2. You are right! You can change the data_root from that line.

**Comment by ziqipang** [comment]
Thanks
