### ISSUE TITLE
why no encoder like detr

### ISSUE THREAD

**Issue by AndyYuan96** [megvii-research/PETR#100]
Hi，I just wonder why your guys not using decoder like origin detr，does the result don‘t have improvement compared with decoder-only？
thanks for kindly reply。

**Comment by yingfei1016** [comment]
Hi,

Vanilla  encoder is difficult to converge. Besides the calculation of encoder is much larger than decoder, which will slow down the model greatly.

Deformable encoder is lightweight and can slightly improve the performance. However we don't want to introduce specially designed operators.

**Comment by AndyYuan96** [comment]
> Hi,
> 
> Vanilla encoder is difficult to converge. Besides the calculation of encoder is much larger than decoder, which will slow down the model greatly.
> 
> Deformable encoder is lightweight and can slightly improve the performance. However we don't want to introduce specially designed operators.

thanks for sharing。
