### ISSUE TITLE
code for petr-e version

### ISSUE THREAD

**Issue by jianingwangind** [megvii-research/PETR#103]
Will you release the code for petr-e? Or could you please share some implementation details?
Thanks

**Comment by yingfei1016** [comment]
Hi，

For PETR-e， you can refer to https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_trainval_cbgs.py , the pretrained weights is from dd3d (https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_trainval_cbgs.py#L243)

For PETRv2, you can refer to https://github.com/megvii-research/PETR/blob/main/projects/configs/denoise/petrv2_vovnet_gridmask_p4_1600x640_dn_trainval_60epoch.py

**Comment by jianingwangind** [comment]
Thanks a lot.

**Comment by loserhou** [comment]
> Hi，
> 
> For PETR-e， you can refer to https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_trainval_cbgs.py , the pretrained weights is from dd3d (https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_trainval_cbgs.py#L243)
> 
> For PETRv2, you can refer to https://github.com/megvii-research/PETR/blob/main/projects/configs/denoise/petrv2_vovnet_gridmask_p4_1600x640_dn_trainval_60epoch.py
> 
> 

Could you please provide your final performance on the test set, or is it the best performance given in the paper?

**Comment by loserhou** [comment]
> Thanks a lot.

Could you please provide your final performance on the test set?thanks!
