### ISSUE TITLE
A mistake about the data pipeline. 

### ISSUE THREAD

**Issue by lidanbingo** [megvii-research/PETR#104]
Hi, yingfei,
 
Thanks for your excellent works.  

I have some questions about your pipeline. You know, you have a lidar2img matrix, and you can project your gt_bboxes to one image according to the corresponding lidar2img matrix. However, I notice some  manipulations exist in you  pipeline,  contributing to some errors in projections, such as GlobalRotScaleTransImage and clip manipulation.  

Before these manipulations, you can have a good projection, 
![no_flip](https://user-images.githubusercontent.com/126806426/222496266-650e653b-33bd-470d-8cc7-26568cfe67ec.png)

After the data pipeline, your projection relationship might be wrong. 
![after manipulation](https://user-images.githubusercontent.com/126806426/222498057-ac9e8915-59e1-4553-a3c5-f8443dad2275.png)

Can you tell me how to tackle this problem? The output boxes might not be similar to the gt_boxes. How to get the right projection relationship? Thanks for your excellent work. Your work will be my first citation. 

if I render the boxes of pts_bbox, I will receive some boxes with offsets.

**Comment by yingfei1016** [comment]
Hi,
    Can you share your visualization code. I always visualize the projected 2D bboxes, which is accurate after GlobalRotScaleTransImage.

**Comment by lidanbingo** [comment]
`from mmdet3d.core.visualizer import (show_multi_modality_result, show_result,
                                     show_seg_result)
import cv2
from util.util import load_cache
show_multi_modality_result(
   data['img'].data[0].permute(1,2,0).cpu().numpy(),
    data['gt_bboxes_3d'].data,
    None,
    data['img_metas'].data['lidar2img'][0],
    "/media/lidan/T7/PETR/figs",
    "fuck",
    box_mode='lidar',
    img_metas=None,
    show=True)
`
You can use this code in the end of Collect3D. Can you share your code? Thanks!

**Comment by yingfei1016** [comment]
Hi,
Our code is redundant, https://drive.google.com/file/d/14teWPq7qhGJaQAa0seuiFZ1G4e4LkenJ/view?usp=sharing .  I feel that there is no mistakes in your code. It may takes some time to find the problem. In fact, the "ResizeCropFlipImage" operation does not increase the performance, it only used to save computation. The "GlobalRotScaleTransImage" will bring some promotion.

**Comment by lidanbingo** [comment]
> 
Well, do you encounter in the same offset error?

**Comment by lidanbingo** [comment]
Actually, the accurate  3D box is very important to me, so will the offset contributes to the errors in prediction?

**Comment by lidanbingo** [comment]
Hi, yingfei, 
can you share a part of your dataset?
The boxes seem to have some offset. 
![temp_resultn015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525](https://user-images.githubusercontent.com/126806426/222900558-b7c0b14c-84e3-46c4-b55b-389cb28e1a0a.jpg)

**Comment by lidanbingo** [comment]
It's really weird. When I remove the ResizeCropFlipImage and GlobalRotScaleTransImage, I can obtain the right projection. However, same offsets will happen when I take them back. 
![temp_resultn015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525](https://user-images.githubusercontent.com/126806426/222901225-fb29bc49-afe1-4d0e-81f1-458c70314d94.jpg)
It is true that these two steps will bring the stability when training. 
Do you know the reason?

**Comment by lidanbingo** [comment]
Or can you provide some cliped images with right boxes? I will close the issue. Thanks!

**Comment by jiaying0w0** [comment]
Hi, i have the same problem, did you find the way to solve it?
Thank you for any help. @lidanbingo @yingfei1016
