### ISSUE TITLE
How to determine the ''resize_lim'' in the ''ida_aug_conf'' according to different input resolutions? 

### ISSUE THREAD

**Issue by xXuHaiyang** [megvii-research/PETR#109]
Hello! A very good work! 

I've mentioned that in `petr_vovnet_gridmask_p4_800x320.py`, we have `ida_aug_conf = {
        "resize_lim": (0.47, 0.625),
        "final_dim": (320, 800),
        "bot_pct_lim": (0.0, 0.0),
        "rot_lim": (0.0, 0.0),
        "H": 900,
        "W": 1600,
        "rand_flip": True,
    }`. In `petr_r50dcn_gridmask_p4.py`, we have `ida_aug_conf = {
        "resize_lim": (0.8, 1.0),
        "final_dim": (512, 1408),
        "bot_pct_lim": (0.0, 0.0),
        "rot_lim": (0.0, 0.0),
        "H": 900,
        "W": 1600,
        "rand_flip": True,
    }`. I wonder that how do we determined the ''resize lim'' according to different input resolution? Is there any recipe? e.g., in the paper we have results of resolution at 384x1056, then in this case what's the ''resize lim''? 

Thanks!

**Comment by yingfei1016** [comment]
Hi,

(704x256), (0.386,0.55)
(800x320), (0.47,0.625)
(1024x384), (0.58,0.83)
(1408x512), (0.8,1.0)
(1600x640), (0.94,1.25)

Some parameters are searched by experiments (1408x512), so they seem irregular. For other input resolution, you can compute the ''resize lim'' base on (1600x640). For example,  the ''resize lim''  is (0.75, 1.0) for (1280x512).
