### ISSUE TITLE
About the bev segmentation branch.

### ISSUE THREAD

**Issue by Zoeeeing** [megvii-research/PETR#11]
Hi, thanks for your great work! I want to ask what is the meaning of the reshape operation in the bev segmentation branch in the paper and where is the corresponding code? Thank you!

**Comment by kvjia** [comment]
We reshape the updated seg queries into several 16*16 blocks and then arrange them together in a predefined order to get the final prediction. You can refer the code at: https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/detectors/petr3d_seg.py#L236

**Comment by Zoeeeing** [comment]
Thanks! It seems like reshape operation is used only during testing? How to use seg query to calculate loss?

**Comment by kvjia** [comment]
Indeed, the reshape operation is only used during testing. During training, we reversely reshape the GT of BEV segmentation to the shape of  seg queries, and then calculate the loss. You can refer the code at: https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/loading.py#L20

**Comment by Zoeeeing** [comment]
Thanks for your quick reply!
