### ISSUE TITLE
cannot pickle 'dict_keys' object

### ISSUE THREAD

**Issue by lianshushu** [megvii-research/PETR#112]
ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'dict_keys' object
ERROR:torch.distributed.elastic.multiprocessing.api:f

**Comment by yingfei1016** [comment]
Hi,
It may the version of mmcv https://github.com/megvii-research/PETR/issues/43 . You can try 
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.9.0/index.html

**Comment by lianshushu** [comment]
thank you ,but hat is not a good solution, I need to change mmdet, mmdet3d, python , pytorch ,cuda to related version too. I want to know wether the bug from this project or mmdet3d relate and I will do the relative debug.

**Comment by yingfei1016** [comment]
Hi,
We have not encountered this mistake. From the error message, may be you can add this code into tools/train.py and tools/test.py. Note that "force" must be True. 
![image](https://user-images.githubusercontent.com/106943722/227432576-b95ad3d3-12d6-414f-b56f-97691c265219.png)

**Comment by lianshushu** [comment]
Thank you very much，It works
