### ISSUE TITLE
Incorrect 3D IoU calculated by function LiDARInstance3DBoxes.overlaps

### ISSUE THREAD

**Issue by YangHan-Morningstar** [megvii-research/PETR#116]
Hi there, thanks for your great work! When I use your PETRv1 model in mmdet3d-0.17.1 to calculate the 3D IoU between two sweep sample, almost all of them are zero, but the visualization is correct. Here are examples

1st sweep sample visualization
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/67748964/231436450-7b74b08d-550f-4b53-8256-5223fffde801.png">

2st sweep sample visualization
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/67748964/231436505-b568a853-7a8b-4a99-a17c-dcdfed2bd118.png">

but the 3D IoU matrix calculated by function LiDARInstance3DBoxes.overlaps are
<img width="642" alt="image" src="https://user-images.githubusercontent.com/67748964/231439551-77cb8257-0694-4a09-90ac-9359e653fa84.png">

here is my code, the value detections0 and detections1 are pred_bbox predicted by PETRv1
```python
from mmdet3d.core import LiDARInstance3DBoxes

###detections0 and detections1 are [N, 7] and [M, 7], respectively. 7 is (x, y, z, w, l, h, -rot-np.pi/2)

a_lidar_instance = LiDARInstance3DBoxes(detections0)
b_lidar_instance = LiDARInstance3DBoxes(detections1)

iou_res = LiDARInstance3DBoxes.overlaps(a_lidar_instance, b_lidar_instance).numpy()
```

I have seen the code getting gt_bbox from nuSences, in mmdet3d-0.17.1, the format is the same as SECOND, which is (x, y, z, w, l, h, -rot-np.pi/2), where rot is in nuScenes. There are no post process so in my opinion, the prediction of the pre-trained PETRv1 is LiDARInstance3DBoxes(x, y, z, w, l, h, -rot-np.pi/2) and the 3D IoU can be directly calculated by function LiDARInstance3DBoxes.overlaps. But as the picture mentioned above, the 3D IoU matrix is wrong.

Please help I find where the problem is. Thanks!

**Comment by yingfei1016** [comment]
I feel that the result may be normal. 3D IOU is very sensitive to depth, and the value of 3D IOU  is much smaller than common 2D IOU. When the depth of two predictions is different, 3D IOU is likely to be 0, but there is no obvious difference in the projection on the 2D image.

**Comment by YangHan-Morningstar** [comment]
Got it, thanks for your reply.
