### ISSUE TITLE
Why does the network uses only the first output of FPN ?

### ISSUE THREAD

**Issue by LoickCh** [megvii-research/PETR#122]
Hello,

Thank you for your great work. I am currently looking to your code and I have a question about the multi-level features. Indeed, in Petr3D_seg (and in other classes):

- forward_train called:
    - extract_feat: outputing a list of several image features using the grid_masking, the backbone, and the neck.
    - forward_pts_train calls self.pts_bbox_head (i.e PETRHead_seg) forward: however, the first line of the forward is 
     **"x = mlvl_feats[self.position_level]"** (https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/dense_heads/petr_head_seg.py#L485)
     
So it means only the first element of the list (since self.position_level equals 0 and is never updated) is used, is not it ? If I am right, only the first element is considered.

**Comment by wayneguo1002** [comment]
Hello, did you solved this problem? I have the same question. Did I miss something? Look forward to your reply, thank you in advance

**Comment by wayneguo1002** [comment]
Oops, i found the merge process. Sorry for bothering(*^▽^*)

**Comment by evercherish** [comment]
> Oops, i found the merge process. Sorry for bothering(_^▽^_)

Hi, could u plz tell me where is the merge process code?

**Comment by autumn-wong** [comment]
> Oops, i found the merge process. Sorry for bothering(_^▽^_)

Hello, I am having a similar problem. Can you point out where this merge process is located in the code?
