### ISSUE TITLE
Questions on extrinsics & intrinsics

### ISSUE THREAD

**Issue by DianCh** [megvii-research/PETR#13]
Hi! Thank you for releasing a wonderful work. I have a few questions regarding the extrinsics & intrinsics processing in `CustomNuScensDataset` and data pipelines, and hope you could help answer:

1. I inspected the values of `extrinsics` of some samples, and found the translation part a bit confusing. For example, two samples have the translations:
```
>>> np.array([extr[-1,:].round(2) for extr in extrinsics])
array([[ 0.01, -0.33, -0.48,  1.  ],
       [ 0.05, -0.34, -0.63,  1.  ],
       [ 0.09, -0.33, -0.54,  1.  ],
       [-0.  , -0.28, -1.  ,  1.  ],
       [-0.24, -0.24, -0.44,  1.  ],
       [ 0.08, -0.27, -0.49,  1.  ]])
# step over to another sample
>>> np.array([extr[-1,:].round(2) for extr in extrinsics])
array([[ 0.01, -0.33, -0.58,  1.  ],
       [ 0.11, -0.34, -0.68,  1.  ],
       [-0.02, -0.33, -0.61,  1.  ],
       [-0.  , -0.28, -0.96,  1.  ],
       [-0.23, -0.24, -0.44,  1.  ],
       [ 0.14, -0.27, -0.47,  1.  ]])
>>> info['cams'].keys()
dict_keys(['CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_FRONT_LEFT', 'CAM_BACK', 'CAM_BACK_LEFT', 'CAM_BACK_RIGHT'])
>>> info['lidar_path']
'./data/nuscenes/samples/LIDAR_TOP/n015-2018-07-18-11-50-34+0800__LIDAR_TOP__1531885881798485.pcd.bin'
```
- Why are the `y` part of the 3 `FRONT` cameras so close to each other? I mean if the vehicle is moving (roughly forward) and each camera is triggered when lidar scan pass through the FOV center, shouldn't the `y` part show the forward movement after a clockwise full scan?
- Why does the `y` part stay almost the same, while `z` part varies noticebly? Is it x-right, y-forward, z-upward?

2. In the customized `transform_3d.py`, why is [line 527 here](https://github.com/megvii-research/PETR/blob/afab7c7026434bd8930812a628817500aa15732f/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L527) commented out? My understanding is that, even though `results["lidar2img"]` is modified accordingly, the `extrinsics` should also be updated if anyone wants to make use of the `extrinsics`.
3. Similar to 2. in `scale_xyz` of `GlobalRotScaleTransImage`, if I want to make use of `intrinsics` myself I should also update `intrinsics`, right? Currently at [line 546](https://github.com/megvii-research/PETR/blob/afab7c7026434bd8930812a628817500aa15732f/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L546) the intrinsics is not modified.

Looking forward to hearing from you. Thanks in advance!

**Comment by yingfei1016** [comment]
Thanks for your concern!
(1) We use mmdet3d==v0.17.1, and the coordinate system is defined as https://github.com/open-mmlab/mmdetection3d/blob/v0.17.1/mmdet3d/core/bbox/structures/lidar_box3d.py#L22. May be the **x** part show the forward movement?
(2) You are right. It is necessary to  update the **extrinsics**! We will fix this problem later.
(3) The transformation of **scale_xyz** is relatively small, so we mainly use it as a disturbance to enhance the robustness. In our practice, modifying the **intrinsics** has the same effect as keeping the **scale_xyz=1.0**, which will get the same **lidar2img**. If you want to make use of intrinsics, you can update intrinsics or set **scale_xyz=1.0**.

**Comment by DianCh** [comment]
Thank you for the reply! As for (1), after a closer look at the `extrinsics` I found that it actually meant the transformation **from lidar to camera**. When `LIDAR_TOP` is used as the sample-level reference frame I guess it's more natural to mean `extrinsics` as **from sensor X to lidar**. In your case it didn't break anything because you were using `lidar2img` and didn't use `extrinsics` explicitly. I made a [tiny PR](https://github.com/megvii-research/PETR/pull/14) that simply applies an inverse - in case you (or other people) want to use `explicitly` later on. After the small fix the translations and rotations make sense to me now:

```
# CAM_FRONT
>>> extrinsics[0].round(2)
array([[ 1.  ,  0.01, -0.  , -0.01],
       [ 0.  ,  0.02,  1.  ,  0.53],
       [ 0.01, -1.  ,  0.02, -0.32],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
# CAM_FRONT_RIGHT
>>> extrinsics[1].round(2)
array([[ 0.55, -0.01,  0.83,  0.5 ],
       [-0.83,  0.02,  0.55,  0.43],
       [-0.03, -1.  ,  0.  , -0.33],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
# CAM_FRONT_LEFT
>>> extrinsics[2].round(2)
array([[ 0.57,  0.  , -0.82, -0.49],
       [ 0.82,  0.02,  0.57,  0.3 ],
       [ 0.02, -1.  ,  0.01, -0.33],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
# CAM_BACK
>>> extrinsics[3].round(2)
array([[-1.  ,  0.01, -0.  , -0.  ],
       [ 0.  ,  0.01, -1.  , -0.98],
       [-0.01, -1.  , -0.01, -0.29],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
# CAM_BACK_LEFT
>>> extrinsics[4].round(2)
array([[-0.32,  0.02, -0.95, -0.48],
       [ 0.95,  0.03, -0.32,  0.09],
       [ 0.02, -1.  , -0.03, -0.25],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
# CAM_BACK_RIGHT
>>> extrinsics[5].round(2)
array([[-0.36, -0.01,  0.93,  0.48],
       [-0.93,  0.04, -0.36, -0.06],
       [-0.04, -1.  , -0.02, -0.28],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])
```

**Comment by yingfei1016** [comment]
Hi,
Thank you for your suggestions, which are very meaningful!
I have updated the code that modify the extrinsics in GlobalRotScaleTransImage ( [L527](https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L527) and [L546](https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L546) ). For the [PR](https://github.com/megvii-research/PETR/pull/14), the ResizeCropFlipImage and LoadMultiViewImageFromMultiSweepsFiles should also changed because of the [L401](https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L401). To avoid many modifications and retrain the network, I added some comments to remind others in the [dataset](https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py#L67).

**Comment by DianCh** [comment]
@yingfei1016 Sounds good! Although I have a second thought regarding [Line 527](https://github.com/megvii-research/PETR/blob/02a6eecc03e5c10b53b1b240519b79e238cf55cb/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L527) and [Line 546]: I think they should both be
```
results["extrinsics"][view] = (torch.tensor(rot_mat @ results["extrinsics"][view]).float()).numpy()
```
because for example, we rotate the boxes around Z by `theta`, the same rotation should apply to the camera rig which is a left-multiplication to the existing extrinsics (since left-multiply is the convention you used in the code); same for the scalilng - let's say we scale the box coordinates by `alpha`, the whole camera rig's translations should expand by `alpha`, too.

**Comment by DianCh** [comment]
Ok I see you're still using **lidar to camera** as extrinsics, then never mind.
