### ISSUE TITLE
Ask for the code of visualization of attention map

### ISSUE THREAD

**Issue by mezhou** [megvii-research/PETR#140]
May I ask for the code of visualization of attention map generated from object query, which was mentioned in the paper. 
![image](https://github.com/megvii-research/PETR/assets/28615093/1712f221-cbdf-46a7-853b-13b5769a52d5)
Thank you very much.

**Comment by Tongjiaxun** [comment]
Hello, have you got the code ?

**Comment by simex-vit** [comment]
@mezhou , @Tongjiaxun Have you got the code for visualizing the attention map ? 

CC: @megvii-model , @ifzhang @eltociear , @junjie18 , @kvjia , @yingfei1016 : Kindly help me with the code to visualize the attention map as mentioned in the paper, if possible please.

**Comment by loserhou** [comment]
> the

do you have the code now？I also want to draw the attention map

**Comment by yingfei1016** [comment]
[visualizer.txt](https://github.com/megvii-research/PETR/files/15413089/visualizer.txt)

The original old code cannot find. This code was written to write the visualization of CMT at that time. Based on the hook mechanism, it should be slightly changed to be easier to use. 
`

**Comment by loserhou** [comment]
> 
> [visualizer.txt](https://github.com/megvii-research/PETR/files/15413089/visualizer.txt)
> 
> The original old code cannot find. This code was written to write the visualization of CMT at that time. Based on the hook mechanism, it should be slightly changed to be easier to use. 
> `

thx!
