### ISSUE TITLE
Could not reproduce results of PETR-vov-p4

### ISSUE THREAD

**Issue by charlesCXK** [megvii-research/PETR#16]
Dear author:
Thanks for sharing such excellent work! I am trying to reproduce your results using the official code, config, and pre-trained weights.
I obtain `NDS: 0.4480, mAP: 0.3983` for `PETR-vov-p4-1600x640`, and `NDS: 0.4202, mAP: 0.3738` for `PETR-vov-p4-800x320`. These numbers are lower than what you report in README. 
I could successfully reproduce the results on R50. Could you give me some advice? Thanks~

**Comment by charlesCXK** [comment]
I follow https://github.com/megvii-research/PETR/blob/main/install.md to install the dependency and run experiments on 8 A100 GPUs.

**Comment by vaesl** [comment]
Hi~Thanks for your attention on our work! As for your question, we also observed similar cases and there is about 0.4-0.7% fluctuation for the VoV-99 backbone. It may due to the difference between GPU machines and our results are produced by 2080ti with a single try.

**Comment by yingfei1016** [comment]
Hi！
I have updated the code and you can train with cbgs by modify the [data](https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_train_cbgs.py#L195)! If you want to train on trainval set further, the pretrained weights of vovnet should also be modified as [L243](https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_1600x640_trainval_cbgs.py#L243).

**Comment by charlesCXK** [comment]
@yingfei1016  Thanks for your kind and quick reply!🤠

**Comment by yingfei1016** [comment]
> @yingfei1016 Sorry to bother you again! I find that if I enable CBGS, the iteration number in each epoch will increase from 3517 to 15448, leading to 4x training time if the total epochs are still 24. May I ask is this normal? Thanks!

Hi, this is a normal phenomenon. The data will be over sampled in CBGS.
