### ISSUE TITLE
Any report for the computation cost?

### ISSUE THREAD

**Issue by Capchenxi** [megvii-research/PETR#18]
Hello, 

Thanks for your excellent work! 
I'm wondering if you have any analysis for the computation cost (params and MACs) of petr models? Or if you have any convenient way to calculate that during inference? I found a "get_flops.py" file under tools folder, but it seems like only support simple input for images rather than a dict containing data and cam_info. 

Thanks.

**Comment by vaesl** [comment]
Sorry for the late reply. We have not conducted the analysis for the computation cost for PETR series. The "get_flops.py" you found in the repo is not used for calculating them. You may try some other ways to calculate them if possible. Actually, the number of params or MACs fails to directly reflect the real inference speed (FPS). In our paper, we only report the inference speed of various input size.
