### ISSUE TITLE
use_lidar=True,     use_camera=True ?

### ISSUE THREAD

**Issue by 24werewolf** [megvii-research/PETR#19]
why  set use_lidar=True ？

**Comment by yingfei1016** [comment]
Hi,
The use_lidar=True and db_sampler don't used in the implementation. The config is follow detr3d, so these arguments don't affect the result. https://github.com/WangYueFt/detr3d/issues/1

**Comment by 24werewolf** [comment]
> Hi, The use_lidar=True and db_sampler don't used in the implementation. The config is follow detr3d, so these arguments don't affect the result. [WangYueFt/detr3d#1](https://github.com/WangYueFt/detr3d/issues/1)

it is a bug.
