### ISSUE TITLE
please how should I visualize the results, I ran test.py and got results.pkl but how should I visualize the results?

### ISSUE THREAD

**Issue by GRE-EXAMINATION** [megvii-research/PETR#20]

**Comment by yunqilingzhen** [comment]
i got the same problem, and i commit my issue minute before. can you describe your problem indetail or have a look at the issue I comment to see if wee have the same problem.

**Comment by GRE-EXAMINATION** [comment]
Yes, we got the same issue. And I think we cannot simply use the tools/misc/visualize_results.py to visualize the results. but I hasn't found better way to solve this...

**Comment by yunqilingzhen** [comment]
yes i’m writing a script to visulize the result, it seems like the aurthors being busy themselves

**Comment by yingfei1016** [comment]
Hello,
We update the code, and you can visualize the result refer to https://github.com/megvii-research/PETR#visualize
