### ISSUE TITLE
Dose "sweep_range" comply with the regulation of nuscenes?

### ISSUE THREAD

**Issue by BB88Lee** [megvii-research/PETR#22]
Thanks for sharing this great work!

I have a question to discuss.
As nuScenes page of detection task mentioned:
"The maximum time window of past sensor data and ego poses that may be used at inference time is approximately 0.5s (at most 6 past camera images, 6 past radar sweeps and 10 past lidar sweeps). At training time there are no restrictions."

Dose "sweep_range=[3, 27]" comply with the regulation?
Is there a standard to use temporal information for camera methods？

**Comment by yingfei1016** [comment]
Hi,
We mainly follow the setting of bevdet4d. As far as we know, BEVformer also use the previous key frames. In our practice, a longer time interval can greatly improve mAP and mAVE.
