### ISSUE TITLE
randomness during inference?

### ISSUE THREAD

**Issue by Capchenxi** [megvii-research/PETR#23]
Hello, 

I have a problem when I'm doing inference part. When I try to put the same data into the model, I got different outputs for the pred 3d bboxes. Could you explain that? Thansk.

**Comment by yingfei1016** [comment]
Hi,
Do you modify some setting?

**Comment by Capchenxi** [comment]
@yingfei1016 
Hello, 
Thanks for your prompt reply. I'm not using the default test.py file in the repo. Instead, I'm applying the visualize.py file form bevfusion(mit) repo. It is using the following code directly where data is from the dataloader. 
```
with torch.inferenc_mode():
    outputs = model(**data, return_loss=False)
```

But I also tried adding a drawing part on the default test.py file after I got all the outputs from single_gpu_test(model, data_loader, args.show, args.show_dir). It seems like the results stay the same foe each time. 

Do you know what caused the randomness if I used the output = model(**data) for inference ? Many thanks!

**Comment by yingfei1016** [comment]
Hello,
We update the code, and you can visualize the result refer to https://github.com/megvii-research/PETR#visualize
