### ISSUE TITLE
How to generate HDmaps-nocover_infos_train/test.pkl? I want to generate this file in my directory rather than /data/Dataset/nuScenes/...

### ISSUE THREAD

**Issue by GRE-EXAMINATION** [megvii-research/PETR#24]

**Comment by GRE-EXAMINATION** [comment]
Dear authors,

Thanks for the great work. Please how should I generate HDmaps-nocover_infos_train/test.pkl file in my directory? I noticed that generate_sweep_pkl.py cannot do this, so could you please give me some advice?

**Comment by yingfei1016** [comment]
Hi,
The HD map segmentation is usually evaluate on the valset, so HDmaps-nocover_infos_train/test.pkl is not need. The generate_sweep_pkl.py is used to generate the pkl for temporal 3D object detection. To build Segmentation dataset, you can
cd tools
python build-dataset.py
