### ISSUE TITLE
Segmentation visualization results

### ISSUE THREAD

**Issue by GRE-EXAMINATION** [megvii-research/PETR#27]
Dear authors,

Thanks for sharing this great work. When I tried to visualize the segmentation results on valset, I found that the visualized segmentation results do not appear to be as good as the paper shows. Despite the fact that the IOU results are quite good, the visualized lane, vehicle, and driving area are somewhat unrecognized. So could you please give me some suggestion to this? and you can find one of visualized segmentation results in the attached picture. Thanks in advance for your help.

(model output)
![f_lane_show_2900](https://user-images.githubusercontent.com/49188756/180216069-4c56e5d2-4920-4775-bfd8-5af754a06dcb.jpg)
(Ground truth)
![gt_map_show_2900](https://user-images.githubusercontent.com/49188756/180216492-8e23df14-3f1c-4dd5-abd0-5f93a9daf2df.jpg)

**Comment by vaesl** [comment]
Hi, thanks for your attention on our work!  In the paper, we select some qualitive results for visulization. As a matter of fact, there are still some hard cases for the proposed method even though the segmentation performance looks good. Moreover, I think our visualization methods are not the same. Later on, we shall release our visualization code at https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/detectors/petr3d_seg.py. You may have a try and check the results.

**Comment by GRE-EXAMINATION** [comment]
@vaesl Thanks so much for your kind reply! looking forward to the release of segmentation visualization code!
