### ISSUE TITLE
Do not find the methods proposed in PETR

### ISSUE THREAD

**Issue by Lizhuoling** [megvii-research/PETR#29]
Hi, in this repo, I do not find the two main contributions of PETR, i.e., 3D coordinate generator and 3D position encoder. There is no encoder in the PETR head, and the position coding seems to be the normal 2D position coding.

**Comment by vaesl** [comment]
Hi, the  3D coordinate generator is located at https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/dense_heads/petr_head.py#L282 while the 3D position encoder is defined at https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/dense_heads/petr_head.py#L259.
