### ISSUE TITLE
About PETRV2 detection results, why no reported results on Res101-dcn?

### ISSUE THREAD

**Issue by YTEP-ZHI** [megvii-research/PETR#30]
![image](https://user-images.githubusercontent.com/48089846/181473167-2bad72c4-ea6d-4194-9508-8672f700a4aa.png)
You only reported detection results based on V2-99 backbone, but I was wondering the results on res101 to make a comparision between PETRV2 and BEVFormer.

**Comment by yingfei1016** [comment]
Hello，
We are conducting experiments on larger backbone. Because of the shortage of computing resources, it has not been trained on res101.  We will make up for these experiments later.
