### ISSUE TITLE
How to generate info files for PETRv2 in 3d detection task？

### ISSUE THREAD

**Issue by dedellzyw** [megvii-research/PETR#31]
Thanks for your nice job! I want to know How to generate info files for PETRv2 in 3d detection task？

**Comment by yingfei1016** [comment]
Hello,
You can refer to  https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py .

**Comment by dedellzyw** [comment]
> Hello, You can refer to https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py .

Thank you！the train info files “mmdet3d_nuscenes_30f_infos_train.pkl” provided by the author is 5.92G, and the author claims to contain 30 previous frames. And the train info files I generated by running generate_sweep_pkl.py is 4.6G. Do I need to modify "num_prev = 5 num_sweep = 5 " in generate_sweep_pkl.py ?

**Comment by yingfei1016** [comment]
You don't need to modify "num_prev = 5 num_sweep = 5 " in generate_sweep_pkl.py. The generate_sweep_pkl.py has been reorganized, so the info file is smaller than before.

**Comment by dedellzyw** [comment]
> You don't need to modify "num_prev = 5 num_sweep = 5 " in generate_sweep_pkl.py. The generate_sweep_pkl.py has been reorganized, so the info file is smaller than before.

I see, thanks a lot!
