### ISSUE TITLE
About the config of petrv2 to achieve the performance

### ISSUE THREAD

**Issue by liangguixing95** [megvii-research/PETR#33]
Hello,
Thanks for your excellent work!
I'm wondering which config of petrv2 can achieve the performance  (mAP0.490/NDS0.582) on the nuScenes test set? Is https://github.com/megvii-research/PETR/blob/main/projects/configs/petrv2/petrv2_vovnet_gridmask_p4_800x320.py this one? or it is not reported yet? And i saw the performance you discribe at the bottom of the config petrv2_vovnet_gridmask_p4_1600x640_trainval_cbgs.py https://github.com/megvii-research/PETR/blob/main/projects/configs/petrv2/petrv2_vovnet_gridmask_p4_1600x640_trainval_cbgs.py achieved such a good performance at mAP: 0.8412/NDS: 0.83, is that a camera only method? how about its performance on the nuScenes test set? why not report its result to the  nuScenes leaderboard?

**Comment by yingfei1016** [comment]
Hi, 
https://github.com/megvii-research/PETR/blob/main/projects/configs/petrv2/petrv2_vovnet_gridmask_p4_1600x640_trainval_cbgs.py is the config that used for nuScenes test set. We reorganized the code, and now we have no resources to retrain it. Therefore, we only put config here.  The mAP: 0.8412/NDS: 0.83 is tested on val set which has overfitted. The results on test set may have a slight difference.
