### ISSUE TITLE
Does the PETR model require point cloud data?

### ISSUE THREAD

**Issue by GuuuuuG** [megvii-research/PETR#35]

**Comment by GuuuuuG** [comment]
It should need a depth map？

**Comment by yingfei1016** [comment]
We only use camera data, both training and testing. We don‘t need depth map and depth estimation.

**Comment by GuuuuuG** [comment]
打扰作者了，刚接触petr的代码不太了解，请问3D PE里面如果没有深度图，那如何构建camera frustum space呢，也就是其中的‘d’

**Comment by yingfei1016** [comment]
因为没有实际的深度，所以沿着深度那个轴进行采样，采64个点。这样就有HxWx64个点，每个点转到3D空间下坐标用x，y，z表示，实际的tensor就是HxWx（64x3），然后用1x1conv变成HxWx256.

**Comment by GuuuuuG** [comment]
> 因为没有实际的深度，所以沿着深度那个轴进行采样，采64个点。这样就有HxWx64个点，每个点转到3D空间下坐标用x，y，z表示，实际的tensor就是HxWx（64x3），然后用1x1conv变成HxWx256.

还有请问v1.0-test的tar包是跟v1.0-trainval01等tar包解压在同一个文件夹里面？为什么没有出现v1.0-test文件夹啊
<img width="322" alt="image" src="https://user-images.githubusercontent.com/110542663/182984737-131e00d4-b9af-4431-ba8b-f3f237305372.png">

**Comment by GuuuuuG** [comment]
> 因为没有实际的深度，所以沿着深度那个轴进行采样，采64个点。这样就有HxWx64个点，每个点转到3D空间下坐标用x，y，z表示，实际的tensor就是HxWx（64x3），然后用1x1conv变成HxWx256.

我用这个预训练模型infer测试集，得出的指标很奇怪如下图所示。
<img width="665" alt="image" src="https://user-images.githubusercontent.com/110542663/182999519-c9b1fc5f-c54a-4bd1-a5cf-17b2e5af70db.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/110542663/182999486-8384d5c3-1633-48e6-9f26-42a8c763542c.png">
而且，我发现导入预训练模型训练时，训练损失跟重新开始训练一样

**Comment by GuuuuuG** [comment]
了解了，打扰您了

--------------原始邮件--------------
发件人："yingfei1016 ***@***.***&gt;;
发送时间：2022年8月4日(星期四) 晚上8:35
收件人："megvii-research/PETR" ***@***.***&gt;;
抄送："GuuuuuG ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [megvii-research/PETR] Does the PETR model require point cloud data? (Issue #35)
-----------------------------------

 

 
因为没有实际的深度，所以沿着深度那个轴进行采样，采64个点。这样就有HxWx64个点，每个点转到3D空间下坐标用x，y，z表示，实际的tensor就是HxWx（64x3），然后用1x1conv变成HxWx256.
