### ISSUE TITLE
About visualize of road segmentation 

### ISSUE THREAD

**Issue by wxiangxiaow** [megvii-research/PETR#37]
Thanks for the great work!
Since the object detection has a visualization, will segmentation also have a visualization demo?

**Comment by kvjia** [comment]
Hi. The segmentation visualization code is in the `simple_test_pts` function. You can find it at https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/detectors/petr3d_seg.py#L248.

**Comment by kvjia** [comment]
You can set the `show_res` as `True` and run the evalation code `tools/dist_test.sh projects/configs/petrv2/petrv2_BEVseg.py work_dirs/petrv2_BEVseg/latest.pth 8 --eval bbox`. The visualization results will be saved at `./res-pre/`.

**Comment by wxiangxiaow** [comment]
Thank you very much! The advise help me a lot!

**Comment by wofeifeileni** [comment]
@wxiangxiaow Hi, have you achieved visualization of segmentation tasks
