### ISSUE TITLE
Can you provide the mmdet3d_nuscenes_30f_infos_train.pkl file generated from the data of the nuscenes mini version?

### ISSUE THREAD

**Issue by zheng-chen777** [megvii-research/PETR#42]

**Comment by zheng-chen777** [comment]
Since I don't have enough hardware resources, I want to use the mini version of the nuscenes dataset to learn your work, but the mmdet3d_nuscenes_30f_infos_train.pkl file downloaded from your Google Drive is generated from the full nuscenes dataset,  I would be grateful if you can provide the mmdet3d_nuscenes_30f_infos_train.pkl file generated by the mini version of the nuscenes dataset

**Comment by yingfei1016** [comment]
Hi，
You can use https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py to generate the temporal pkl. 
You may need to modify https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py#L23  and https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py#L27. 

For hardware resources,  you can refer  https://github.com/megvii-research/PETR/issues/41#issuecomment-1212779951 to train on a single gpu.  The nuscenes v1.0-mini is too small, it may don't converge.

To reduce the datasets, you can also set load_interval>1 https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L121. It will downsample the dataset.

**Comment by zheng-chen777** [comment]
Thank you so much for such a detailed answer, it was very useful to me
