### ISSUE TITLE
Cannot reproduce PTERv2 results

### ISSUE THREAD

**Issue by PhoneSix** [megvii-research/PETR#46]
Hi， @yingfei1016 ，I tried to reproduce the results with the default config on VoVNet on A100, but got a bit lower results. I got 49.6 NDS and 40.3 mAP. Results recorded in the config are 50.3 NDS and 41 mAP. Is it normal?

**Comment by yingfei1016** [comment]
Hi，
The result is normal. In our paper, the result is 49.6 NDS and 40.1 mAP.
![image](https://user-images.githubusercontent.com/106943722/187595227-7d37b8de-ae3b-4914-8ccc-f90b72b9218d.png)
The result of github is retrained and  surprising to be higher than the paper. The normal result should around 49.6 NDS and 40.5 mAP.

**Comment by PhoneSix** [comment]
Get. Thanks!
