### ISSUE TITLE
Log of loss curves

### ISSUE THREAD

**Issue by Lizhuoling** [megvii-research/PETR#47]
Hi, can you share the log files of training process? When I use the official log files to train models, the loss seems not to drop. I want to see how the loss curve should be when the training process is proper.

**Comment by vaesl** [comment]
![image](https://user-images.githubusercontent.com/35247395/188105051-68dbf27b-b156-410d-9cd4-66f3c314cf9b.png)

We have provided the log files in the Readme file, please check it. As for the training issue, are you following the default settings with 8x 2080ti GPU?

**Comment by Lizhuoling** [comment]
> 

I use 4 RTX3090 GPU, so the batch size is 4. Although the batch size is not 8, I think the convergence should only be dropped slightly. The current phenomenon is the network almost not converges using the official configuration file. I am still checking what is wrong.

**Comment by yingfei1016** [comment]
Hi，
When use 4 RTX3090 GPU,  you can set "samples_per_gpu=2," and keep the "lr=2e-4".  
or set "samples_per_gpu=4," and use the "lr=4e-4" (**recommend**).

**Comment by yingfei1016** [comment]
Here are some log and config https://drive.google.com/drive/folders/1fGbPOw3OWwZ23_AtxNnLB_v_DoRWQdoX?usp=sharing .
These model are trained on 4GPUs with bs 1,2,4 .
