### ISSUE TITLE
作者您好，可否告知一下模型训练的显卡型号以及训练时间？谢谢！

### ISSUE THREAD

**Issue by qhfan** [megvii-research/PETR#49]
作者您好，可否告知一下模型训练的显卡型号以及训练时间？谢谢！

**Comment by yingfei1016** [comment]
您好！
您想看什么模型的时间，readme上展示的模型都是在2080ti上训练，详细训练环境以及时间可在对应log中看到。

**Comment by qhfan** [comment]
哦哦，感谢您的回复，已经看到了，麻烦您了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月12日(周一) 晚上8:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [megvii-research/PETR] 作者您好，可否告知一下模型训练的显卡型号以及训练时间？谢谢！ (Issue #49)




 
您好！
 您想看什么模型的时间，readme上展示的模型都是在2080ti上训练，详细训练环境以及时间可在对应log中看到。
