### ISSUE TITLE
memory increase and then crash when start dist

### ISSUE THREAD

**Issue by zyc4me** [megvii-research/PETR#50]
thank you for sharing the code~
i met the problom when start dist_train.sh

swap mem increase to full, then crashed, got error 
![image](https://user-images.githubusercontent.com/34511872/190323694-b2d86beb-ccbe-4472-b34a-a32bee186407.png)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 8530) of binary: /opt/miniconda3/envs/petr/bin/python3
Traceback (most recent call last):
  File "/opt/miniconda3/envs/petr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/miniconda3/envs/petr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/run.py", line 692, in run
    )(*cmd_args)
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/miniconda3/envs/petr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
************************************************
             tools/train.py FAILED
================================================
Root Cause:
[0]:
  time: 2022-09-15_05:47:52
  rank: 2 (local_rank: 2)
  exitcode: -9 (pid: 8530)
  error_file: <N/A>
  msg: "Signal 9 (SIGKILL) received by PID 8530"
================================================
Other Failures:
  <NO_OTHER_FAILURES>
************************************************

my environment:
 - C++ Version: 201402                                                                                                                                                                            [1847/1847]
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_
75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUS
E_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-
missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-type
defs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-col
or=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PE
RF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.9.0+cu111
OpenCV: 4.2.0
MMCV: 1.4.0
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.2
MMDetection: 2.24.1
MMSegmentation: 0.20.2
MMDetection3D: 0.17.1+9a62051

**Comment by yingfei1016** [comment]
Hi，
Do you train the petrv2. For 8 gpus, you should have >300g memory space.
You can set workers_per_gpu=2 or use https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py to generate a small pkl file.

**Comment by zyc4me** [comment]
>thank you!!!
 yes, train the petrv2,  it can be start traing  when use 1 gpu, but when use 4 gpu, set workers_per_gpu to 0 or 1  always has the problom,  is all data loading to memory when training?   is there a solution to deal with the memory usage if i just want to train the whole dataset? 300G is so huge~~

**Comment by yingfei1016** [comment]
The main reason is the "mmdet3d_nuscenes_30f_infos_train.pkl", this file is about 6G. So the total memory must > 6G x num_gpus x worker_nums . For 8 gpus and 4 workers, the memory for "mmdet3d_nuscenes_30f_infos_train.pkl" must  > 200G. Considering other files, the space should be greater than 300g.

To save memory, you should reduce the space of "mmdet3d_nuscenes_30f_infos_train.pkl". The space mainly cost for the sweep infos (30 frames). You can load this pkl and reduce the sweep infos. For example, sample the sweep infos with the interval of 3.
Delete the 0-3 sweep frame and 27 -30 frame.  Delete some useless parameters in sweep infos.

Besides, the pkl files generate from https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py is about  5.0g . You can start from it.

**Comment by zyc4me** [comment]
I'm already using this file" mmdet3d_nuscenes_30f_infos_train.pkl" generate from [](https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py), it's 4.81G,  and  exp config is .projects/configs/petrv2/petrv2_vovnet_gridmask_p4_800x320.py
workers_per_gpu set to 1, 
num_gpus is 4,  
samples_per_gpu is 1,
gpu is 2080ti, 
is also have the problem,.....,do you have any other suggestions....

when i set to  single gpu,
workers_per_gpu set to 4,
 num_gpus is 1,
 samples_per_gpu is 4,
can  train normally...

**Comment by zyc4me** [comment]
thank you!!
one more question,  is 4.81G * 4(num_gpus) * 1(samples_per_gpu)   use total 128G memory when using multi gpu? is that normal?   
multigpu  single gpu   the value is same

**Comment by yingfei1016** [comment]
I think the memory cost is normal. You can follow this code to sample 2 frames or more frames.

```
import pickle
from nuscenes import NuScenes
import numpy as np
from pyquaternion import Quaternion
import numpy as np
import os
import mmcv
import tqdm
import copy
sensors = ['CAM_FRONT', 'CAM_FRONT_RIGHT', 'CAM_BACK_RIGHT', 'CAM_BACK', 'CAM_BACK_LEFT', 'CAM_FRONT_LEFT']
info_prefix = 'train'
data_root = "/data/Dataset/nuScenes/"

info_path = os.path.join(data_root,'mmdet3d_nuscenes_30f_infos_{}.pkl'.format(info_prefix))
key_infos = pickle.load(open(info_path, 'rb'))
pseudo_path = os.path.join(data_root,'mmdet3d_nuscenes_2f_infos_{}.pkl'.format(info_prefix))

pseudo_infos = []
for current_id in tqdm.tqdm(range(len(key_infos['infos']))):
    key_info = copy.deepcopy(key_infos['infos'][current_id])
    numsweep = len(key_info['sweeps'])
    if numsweep > 0:
        key_info['sweeps'] = [key_info['sweeps'][min(15, numsweep) - 1]]
    pseudo_infos.append(key_info)

key_infos['infos'] = pseudo_infos
mmcv.dump(key_infos, pseudo_path)
```
