### ISSUE TITLE
About the matching cost

### ISSUE THREAD

**Issue by PhoneSix** [megvii-research/PETR#58]
Hi, @yingfei1016 . I found that the predicted velocity was not in the matching cost. Could you kindly explain it? Lots of thanks!

**Comment by yingfei1016** [comment]
Hi，
This is following [detr3d](https://github.com/WangYueFt/detr3d/blob/main/projects/mmdet3d_plugin/core/bbox/assigners/hungarian_assigner_3d.py#L111) .
I think the main reason may from two aspects:
(1) According to experience in 2D object detection, label assign generally adopt some physical attributes such as location and IOU. The velocity has no relation with these attributes. 
(2) DETR3D is a single frame methods. In essence, single frame can't predict the speed. The error of speed is very large, which may mislead the matching.

**Comment by PhoneSix** [comment]
Thanks very much for your quick reply. I wonder whether you conduct experiments on including them in the matching cost of PETR v2, since PETR v2 greatly reduce the error of speed.

**Comment by feifei-Liu** [comment]
Hi,
I retrained the model, and here are two results:
**(1) math cost without  velocity**
mAP: 0.4025                                                                                                                               
mATE: 0.7372
mASE: 0.2710
mAOE: 0.4455                                                                                                                                                        
mAVE: 0.4180                                                                                                                                                        
mAAE: 0.1953
NDS: 0.4946
Eval time: 187.9s                                                                                                                                                                                                                                                                                                                       Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.578   0.537   0.150   0.072   0.360   0.190                                                                                                               truck   0.359   0.754   0.209   0.093   0.343   0.220
bus     0.429   0.822   0.207   0.090   0.800   0.237
trailer 0.213   0.950   0.244   0.559   0.294   0.168
construction_vehicle    0.127   1.118   0.484   1.219   0.147   0.365                                                                                               pedestrian      0.486   0.673   0.291   0.528   0.437   0.190
motorcycle      0.403   0.679   0.258   0.556   0.661   0.174
bicycle 0.389   0.607   0.260   0.750   0.302   0.018
traffic_cone    0.559   0.552   0.322   nan     nan     nan
barrier 0.480   0.679   0.286   0.142   nan     nan
**(2) math cost with velocity**
mAP: 0.4034
mATE: 0.7525
mASE: 0.2673
mAOE: 0.4524
mAVE: 0.3672
mAAE: 0.1933
NDS: 0.4984
Eval time: 177.4s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.583   0.531   0.150   0.075   0.313   0.194
truck   0.378   0.745   0.209   0.103   0.332   0.221
bus     0.412   0.833   0.201   0.095   0.684   0.247
trailer 0.227   1.144   0.225   0.722   0.273   0.135
construction_vehicle    0.123   1.083   0.485   1.130   0.129   0.352
pedestrian      0.482   0.691   0.292   0.527   0.439   0.194
motorcycle      0.404   0.687   0.256   0.542   0.524   0.190
bicycle 0.396   0.573   0.247   0.739   0.244   0.014
traffic_cone    0.551   0.551   0.319   nan     nan     nan
barrier 0.479   0.688   0.289   0.138   nan     nan

When calculate match cost with velocity, mAVE will be greatly improved, other attributes (mATE, mAOE) will be slightly decreased, and the overall NDS improvement is not obvious.

**Comment by yingfei1016** [comment]
Hi,
I retrained the model, and here are two results:
**(1) math cost without  velocity**
mAP: 0.4025                                                                                                                               
mATE: 0.7372
mASE: 0.2710
mAOE: 0.4455                                                                                                                                                        
mAVE: 0.4180                                                                                                                                                        
mAAE: 0.1953
NDS: 0.4946
Eval time: 187.9s                                                                                                                                                                                                                                                                                                                       Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.578   0.537   0.150   0.072   0.360   0.190                                                                                                               truck   0.359   0.754   0.209   0.093   0.343   0.220
bus     0.429   0.822   0.207   0.090   0.800   0.237
trailer 0.213   0.950   0.244   0.559   0.294   0.168
construction_vehicle    0.127   1.118   0.484   1.219   0.147   0.365                                                                                               pedestrian      0.486   0.673   0.291   0.528   0.437   0.190
motorcycle      0.403   0.679   0.258   0.556   0.661   0.174
bicycle 0.389   0.607   0.260   0.750   0.302   0.018
traffic_cone    0.559   0.552   0.322   nan     nan     nan
barrier 0.480   0.679   0.286   0.142   nan     nan
**(2) math cost with velocity**
mAP: 0.4034
mATE: 0.7525
mASE: 0.2673
mAOE: 0.4524
mAVE: 0.3672
mAAE: 0.1933
NDS: 0.4984
Eval time: 177.4s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.583   0.531   0.150   0.075   0.313   0.194
truck   0.378   0.745   0.209   0.103   0.332   0.221
bus     0.412   0.833   0.201   0.095   0.684   0.247
trailer 0.227   1.144   0.225   0.722   0.273   0.135
construction_vehicle    0.123   1.083   0.485   1.130   0.129   0.352
pedestrian      0.482   0.691   0.292   0.527   0.439   0.194
motorcycle      0.404   0.687   0.256   0.542   0.524   0.190
bicycle 0.396   0.573   0.247   0.739   0.244   0.014
traffic_cone    0.551   0.551   0.319   nan     nan     nan
barrier 0.479   0.688   0.289   0.138   nan     nan

When calculate match cost with velocity, mAVE will be greatly improved, other attributes (mATE, mAOE) will be slightly decreased, and the overall NDS improvement is not obvious.

**Comment by PhoneSix** [comment]
Thanks a lot!
