### ISSUE TITLE
The data preparation of petrv2

### ISSUE THREAD

**Issue by evakasch** [megvii-research/PETR#6]
hi, the train dataset used in petrv2 experiments is "mmdet3d_nuscenes_30f_infos_train.pkl", and is there any code to create the data? I follow the readme instruction to use the code offered by the official mmdet, but it can only generate "nuscenes_infos_train.pkl", but not "mmdet3d_nuscenes_30f_infos_train.pkl".

**Comment by yingfei1016** [comment]
Hi, as description in README.md，the info files can be download from https://drive.google.com/drive/folders/1_C2yuh51ROF3UzId4L1itwGQVUeVUxU6?usp=sharing or https://pan.baidu.com/s/10dpbLS64phuG-0n1WWB9Cw#list/path=%2F.  We will prepare the code of dataprocess  as soon as possible, as we explained in https://github.com/megvii-research/PETR/issues/4.
