### ISSUE TITLE
in petrv2, Which parts of the code do the timing embody

### ISSUE THREAD

**Issue by guohao02** [megvii-research/PETR#60]

**Comment by yingfei1016** [comment]
Hi，
（1）Temporal alignment is placed in the data processing https://github.com/megvii-research/PETR/blob/main/tools/generate_sweep_pkl.py.
（2）We load the sweep data in pipeline https://github.com/megvii-research/PETR/blob/main/projects/configs/petrv2/petrv2_vovnet_gridmask_p4_800x320.py#L161. The sweep data is concat with key frame data at view axis ( (B, 6, 3, H, W) -> (B, 12, 3, H, W) ). Then the data augmentation and training can be performed similar with single frame.

**Comment by exiawsh** [comment]
Hello,
I also conducted research on PETRV2. Here are some of my understandings：
（1）There are no explicit time positional embedding, so they regression the position offset instead.
（2）The way to distinguish the time is the multi-view embbeding. ![图片](https://user-images.githubusercontent.com/74858581/193246214-181804c7-fcb6-4c64-a033-9cefd3180143.png)
MV in the table. That's may cause the generalization problem in the real application. But I found you can encode the time delay by using sincos embedding, which may cause similiar results (slightly poor in mAVE).
