### ISSUE TITLE
a question of this permutation

### ISSUE THREAD

**Issue by FANG-MING** [megvii-research/PETR#61]
https://github.com/megvii-research/PETR/blob/2f55c1597e39c4d89dfd8ef07df29a955299d5fc/projects/mmdet3d_plugin/models/dense_heads/petrv2_dnhead.py#L370
why there is (W, H, D) not (H, W, D) ？

**Comment by yingfei1016** [comment]
For coordinate transformation, (x, y, d) is used in image space, so we should put W in front.
