### ISSUE TITLE
Hi, what's the difference between these two pretrained backbones?

### ISSUE THREAD

**Issue by tuoyuxiang** [megvii-research/PETR#75]
I found two backbones that used in config, one is v2-99 `fcos3d_vovnet_imgbackbone-remapped.pth` and another is    `dd3d_det_final.pth `,  and `dd3d` is used for nuScenes TEST,  I wonder what's the difference? Thanks~!

**Comment by yingfei1016** [comment]
**fcos3d_vovnet_imgbackbone-remapped.pth**  is first pretrained on DDAD15M dataset and further trained on nuScenes **train set** with FCOS3D.

**dd3d_det_final.pth**  is first pretrained on DDAD15M dataset and further trained on nuScenes **trainval set** with DD3D. 

The 'dd3d_det_final.pth' may have **overfitted of the val set**, the result will be inflated. So if you report the result on val set，you must use the  'fcos3d_vovnet_imgbackbone-remapped.pth'.

**Comment by tuoyuxiang** [comment]
Got it, thanks!
