### ISSUE TITLE
Question about coords_mask

### ISSUE THREAD

**Issue by toyot-li** [megvii-research/PETR#76]
Hi, thanks for the nice work. I am confused about this condition https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/models/dense_heads/petr_head.py#L321 . Could you please explain its meaning and intuition? I did not find related descriptions in the original paper. Thanks.

**Comment by yingfei1016** [comment]
> @yingfei1016 Thanks for your reply! So if I understand correctly, this line just applies a heuristic strategy to filter out far-away 3D points, right?

Yes！
