### ISSUE TITLE
Is the order of regression wrong here?

### ISSUE THREAD

**Issue by tuoyuxiang** [megvii-research/PETR#78]
Hi, 
If I set `with_multi=True`, there will use multi groups for bbox regression, and the order here is `xy, z, size, rot, velo`:
https://github.com/megvii-research/PETR/blob/7b046e28a03dcb296987eb3e76cbf761f52a37f0/projects/mmdet3d_plugin/models/dense_heads/petrv2_head.py#L62
but the output of regression are in order of `cx, cy, w, l, cz, h, rot_sine, rot_cosine, vx, vy`:
https://github.com/megvii-research/PETR/blob/7b046e28a03dcb296987eb3e76cbf761f52a37f0/projects/mmdet3d_plugin/core/bbox/coders/nms_free_coder.py#L55
Is there a bug or not? 
Thanks!  @yingfei1016

**Comment by yingfei1016** [comment]
Yes, there are inconsistencies here. You can train it according to the correct size, but the result has little effect.
