### ISSUE TITLE
What is the purpose of the reverse_angle of the GlobalRotScaleTransImage?

### ISSUE THREAD

**Issue by Yzichen** [megvii-research/PETR#8]
My understanding is that rot_angle is the rotation angle of 3D space, so the angle of rotation of gt_boxes should also be rot_angle, why should it be reversed?

**Comment by vaesl** [comment]
> My understanding is that rot_angle is the rotation angle of 3D space, so the angle of rotation of gt_boxes should also be rot_angle, why should it be reversed?

Hi, we use the v0.17.1 version of mmdet3d. The rotation transformation in mmdet3d (refer to https://github.com/open-mmlab/mmdetection3d/blob/v0.17.1/mmdet3d/core/bbox/structures/lidar_box3d.py#L149) is achieved in clock-wise manner.  While the basepoints (https://github.com/open-mmlab/mmdetection3d/blob/v0.17.1/mmdet3d/core/points/base_points.py#L173) are rotated in counterclockwise manner. So we need to make it reverse.

**Comment by Yzichen** [comment]
Ok, I understand, thanks for your reply. I'm using mmdet3d after the coordinate system reconstruction, rotation is all counter-clockwise, so I won't need to take the reverse.

**Comment by vaesl** [comment]
Yeah, there is no need to do that after the reconstruction.
