### ISSUE TITLE
A bug for transform matrix

### ISSUE THREAD

**Issue by djiajunustc** [megvii-research/PETR#92]
Hi,

I found a bug here:
https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L669

It should be:
results["lidar2cam"][view] = (rot_mat_inv.T @ torch.tensor(results["lidar2cam"][view]).float()).numpy()

Best,
Jiajun

**Comment by djiajunustc** [comment]
results["extrinsics"][view] = (rot_mat_inv.T @ torch.tensor(results["extrinsics"][view]).float()).numpy()

**Comment by junjie18** [comment]
Hi jiajun,
We have fix it, thx.
