### ISSUE TITLE
weird behavior when combining FPN and `find_unused_parameters`

### ISSUE THREAD

**Issue by toyot-li** [megvii-research/PETR#98]
@yingfei1016 `CPFPN` is introduced to remove unused parameters that do not receive gradients in vanilla FPN, i.e. `img_neck.fpn_convs.1.conv.bias` and `img_neck.fpn_convs.1.conv.weight`. When I replace `CPFPN` [here](https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_800x320.py#L37) with `FPN` (in the original mmdet) and set `find_unused_parameters=True` [here](https://github.com/megvii-research/PETR/blob/main/projects/configs/petr/petr_vovnet_gridmask_p4_800x320.py#L231) and set `with_cp=False` for `PETRTransfomerDecoder`, I expected to see a runtime error since FPN includes unused parameters now, but I **did not** see such errors and the training starts normally.

What could be the underlying reasons? Are there any other operations in the code preventing this? Thanks.

**Comment by yingfei1016** [comment]
Hi，
Set **find_unused_parameters=True ，with_cp=True** will see the errors.  
**with_cp** is  conflict with **find_unused_parameters**, so if use **with_cp=True** to save memory, find_unused_parameters must be False.

**Comment by yingfei1016** [comment]
Whenever the network exists ununsed parameters,  **find_unsed_parameters=True** will be send into DDP and solve the errors. So the training goes successfully is normal.
