### ISSUE TITLE
The initialization weight of VovNet.

### ISSUE THREAD

**Issue by Daniel-xsy** [megvii-research/PETR#99]
Thanks for your great work!  I just wondering about the initialization weight of PETR-Vov reported in the official paper (or this codebase). Do you use the DD3D to initialize the VovNet or train it from scratch? Thanks so much.

**Comment by yingfei1016** [comment]
Hi,

Our V2-99 is pretrained on DDAD15M ([weights](https://tri-ml-public.s3.amazonaws.com/github/dd3d/pretrained/depth_pretrained_v99-3jlw0p36-20210423_010520-model_final-remapped.pth)) and further trained on nuScenes **train** set with FCOS3D.  

Note that DD3D weights is  pretrained on DDAD15M and further trained on nuScenes **trainval** set with DD3D

**Comment by Daniel-xsy** [comment]
@yingfei1016 Thanks for your information!
